---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-adguard-home"
  ADDON_SLUG: "adguard"
  ADDON_TARGET: "adguard"

  ADDON_AARCH64_BASE: "hassioaddons/base-aarch64:8.0.5"
  ADDON_AMD64_BASE: "hassioaddons/base-amd64:8.0.5"
  ADDON_ARMHF_BASE: "hassioaddons/base-armhf:8.0.5"
  ADDON_ARMV7_BASE: "hassioaddons/base-armv7:8.0.5"
  ADDON_I386_BASE: "hassioaddons/base-i386:8.0.5"
